// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskManagement.Infrastructure;

#nullable disable

namespace TaskManagement.Infrastructure.Migrations
{
    [DbContext(typeof(TaskManagementAppDbContext))]
    [Migration("20250927075551_addseeddata")]
    partial class addseeddata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskManagement.Domain.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("CreatorId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5e99f847-c577-45b2-80c4-8845772f6af8"),
                            AssigneeId = new Guid("c5a48572-e460-42c8-bc99-fe610187860c"),
                            CreatedAt = new DateTime(2025, 9, 27, 7, 55, 45, 303, DateTimeKind.Utc).AddTicks(7419),
                            CreatorId = new Guid("4315bea9-26b4-4e81-a627-fd76c9a0b539"),
                            Description = "Initialize git and CI pipeline",
                            Priority = "HIGH",
                            Status = 0,
                            Title = "Setup project repo",
                            UpdatedAt = new DateTime(2025, 9, 27, 7, 55, 45, 303, DateTimeKind.Utc).AddTicks(7425)
                        },
                        new
                        {
                            Id = new Guid("e7ec0db2-4c41-473f-9195-055af97aa543"),
                            AssigneeId = new Guid("4315bea9-26b4-4e81-a627-fd76c9a0b539"),
                            CreatedAt = new DateTime(2025, 9, 27, 7, 55, 45, 303, DateTimeKind.Utc).AddTicks(9262),
                            CreatorId = new Guid("4315bea9-26b4-4e81-a627-fd76c9a0b539"),
                            Description = "ER diagram for tasks & users",
                            Priority = "MEDIUM",
                            Status = 1,
                            Title = "Design DB schema",
                            UpdatedAt = new DateTime(2025, 9, 27, 7, 55, 45, 303, DateTimeKind.Utc).AddTicks(9262)
                        },
                        new
                        {
                            Id = new Guid("24b50946-8da5-49a6-8299-13c40fa69e11"),
                            AssigneeId = new Guid("c5a48572-e460-42c8-bc99-fe610187860c"),
                            CreatedAt = new DateTime(2025, 9, 27, 7, 55, 45, 303, DateTimeKind.Utc).AddTicks(9268),
                            CreatorId = new Guid("4315bea9-26b4-4e81-a627-fd76c9a0b539"),
                            Description = "JWT authentication",
                            Priority = "HIGH",
                            Status = 2,
                            Title = "Implement login API",
                            UpdatedAt = new DateTime(2025, 9, 27, 7, 55, 45, 303, DateTimeKind.Utc).AddTicks(9268)
                        },
                        new
                        {
                            Id = new Guid("c508fd54-9648-4a0f-b1f4-6515800f5908"),
                            AssigneeId = new Guid("c5a48572-e460-42c8-bc99-fe610187860c"),
                            CreatedAt = new DateTime(2025, 9, 27, 7, 55, 45, 303, DateTimeKind.Utc).AddTicks(9272),
                            CreatorId = new Guid("c5a48572-e460-42c8-bc99-fe610187860c"),
                            Description = "Task board columns",
                            Priority = "LOW",
                            Status = 0,
                            Title = "Frontend dashboard",
                            UpdatedAt = new DateTime(2025, 9, 27, 7, 55, 45, 303, DateTimeKind.Utc).AddTicks(9272)
                        },
                        new
                        {
                            Id = new Guid("526981c8-33f2-4f4e-8693-42c40b5b9f52"),
                            AssigneeId = new Guid("c5a48572-e460-42c8-bc99-fe610187860c"),
                            CreatedAt = new DateTime(2025, 9, 27, 7, 55, 45, 303, DateTimeKind.Utc).AddTicks(9289),
                            CreatorId = new Guid("4315bea9-26b4-4e81-a627-fd76c9a0b539"),
                            Description = "Update CI/CD pipeline",
                            Priority = "HIGH",
                            Status = 0,
                            Title = "Update CI/CD",
                            UpdatedAt = new DateTime(2025, 9, 27, 7, 55, 45, 303, DateTimeKind.Utc).AddTicks(9290)
                        },
                        new
                        {
                            Id = new Guid("007b470b-3f6a-45d2-803e-61d20f227977"),
                            AssigneeId = new Guid("4315bea9-26b4-4e81-a627-fd76c9a0b539"),
                            CreatedAt = new DateTime(2025, 9, 27, 7, 55, 45, 303, DateTimeKind.Utc).AddTicks(9301),
                            CreatorId = new Guid("4315bea9-26b4-4e81-a627-fd76c9a0b539"),
                            Description = "Validate all user Data",
                            Priority = "MEDIUM",
                            Status = 1,
                            Title = "DB Validation",
                            UpdatedAt = new DateTime(2025, 9, 27, 7, 55, 45, 303, DateTimeKind.Utc).AddTicks(9301)
                        },
                        new
                        {
                            Id = new Guid("56a3c0ce-fb67-4463-809d-864df4bfa825"),
                            AssigneeId = new Guid("c5a48572-e460-42c8-bc99-fe610187860c"),
                            CreatedAt = new DateTime(2025, 9, 27, 7, 55, 45, 303, DateTimeKind.Utc).AddTicks(9305),
                            CreatorId = new Guid("4315bea9-26b4-4e81-a627-fd76c9a0b539"),
                            Description = "JWT authentication validation",
                            Priority = "HIGH",
                            Status = 2,
                            Title = "Auth Validation",
                            UpdatedAt = new DateTime(2025, 9, 27, 7, 55, 45, 303, DateTimeKind.Utc).AddTicks(9305)
                        },
                        new
                        {
                            Id = new Guid("c6d9e093-abd2-4e83-9ab6-9699667781b0"),
                            AssigneeId = new Guid("c5a48572-e460-42c8-bc99-fe610187860c"),
                            CreatedAt = new DateTime(2025, 9, 27, 7, 55, 45, 303, DateTimeKind.Utc).AddTicks(9308),
                            CreatorId = new Guid("c5a48572-e460-42c8-bc99-fe610187860c"),
                            Description = "Task board columns",
                            Priority = "LOW",
                            Status = 0,
                            Title = "Task Board",
                            UpdatedAt = new DateTime(2025, 9, 27, 7, 55, 45, 303, DateTimeKind.Utc).AddTicks(9309)
                        });
                });

            modelBuilder.Entity("TaskManagement.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4315bea9-26b4-4e81-a627-fd76c9a0b539"),
                            CreatedAt = new DateTime(2025, 9, 27, 7, 55, 44, 653, DateTimeKind.Utc).AddTicks(4760),
                            Email = "admin@example.com",
                            PasswordHash = "$2a$11$htj6fGbknvRj2Zx6p/mSuOAb4pEFE2tF8RjrJeePqlX1EX59h/sOS",
                            Role = 1,
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("c5a48572-e460-42c8-bc99-fe610187860c"),
                            CreatedAt = new DateTime(2025, 9, 27, 7, 55, 44, 967, DateTimeKind.Utc).AddTicks(4595),
                            Email = "user@example.com",
                            PasswordHash = "$2a$11$SIYDn2ABuY4Se4nsmzqzLuMjjUqPVSli0ZCW3w0jNGWzbMgJsvTHG",
                            Role = 0,
                            Username = "user"
                        });
                });

            modelBuilder.Entity("TaskManagement.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("TaskManagement.Domain.Entities.User", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeId");

                    b.HasOne("TaskManagement.Domain.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId");

                    b.Navigation("Assignee");

                    b.Navigation("Creator");
                });
#pragma warning restore 612, 618
        }
    }
}
