// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskManagement.Infrastructure;

#nullable disable

namespace TaskManagement.Infrastructure.Migrations
{
    [DbContext(typeof(TaskManagementAppDbContext))]
    partial class TaskManagementAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskManagement.Domain.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("CreatorId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("763b1f75-aac3-448b-91c9-522d0331cc7b"),
                            AssigneeId = new Guid("7f8250de-1646-4a70-b675-fc13d7bfa94d"),
                            CreatedAt = new DateTime(2025, 9, 27, 8, 1, 5, 812, DateTimeKind.Utc).AddTicks(878),
                            CreatorId = new Guid("8ab106de-325b-48d8-9fe5-08099049fe89"),
                            Description = "Initialize git and CI pipeline",
                            Priority = "HIGH",
                            Status = 0,
                            Title = "Setup project repo",
                            UpdatedAt = new DateTime(2025, 9, 27, 8, 1, 5, 812, DateTimeKind.Utc).AddTicks(884)
                        },
                        new
                        {
                            Id = new Guid("7f621b5d-abed-420a-b02d-554f8f96fce5"),
                            AssigneeId = new Guid("8ab106de-325b-48d8-9fe5-08099049fe89"),
                            CreatedAt = new DateTime(2025, 9, 27, 8, 1, 5, 812, DateTimeKind.Utc).AddTicks(2155),
                            CreatorId = new Guid("8ab106de-325b-48d8-9fe5-08099049fe89"),
                            Description = "ER diagram for tasks & users",
                            Priority = "MEDIUM",
                            Status = 1,
                            Title = "Design DB schema",
                            UpdatedAt = new DateTime(2025, 9, 27, 8, 1, 5, 812, DateTimeKind.Utc).AddTicks(2156)
                        },
                        new
                        {
                            Id = new Guid("44848876-29d2-4496-8e09-94e346406f39"),
                            AssigneeId = new Guid("7f8250de-1646-4a70-b675-fc13d7bfa94d"),
                            CreatedAt = new DateTime(2025, 9, 27, 8, 1, 5, 812, DateTimeKind.Utc).AddTicks(2160),
                            CreatorId = new Guid("8ab106de-325b-48d8-9fe5-08099049fe89"),
                            Description = "JWT authentication",
                            Priority = "HIGH",
                            Status = 2,
                            Title = "Implement login API",
                            UpdatedAt = new DateTime(2025, 9, 27, 8, 1, 5, 812, DateTimeKind.Utc).AddTicks(2160)
                        },
                        new
                        {
                            Id = new Guid("c7f07bde-448f-4901-8dd8-79264b60ddc9"),
                            AssigneeId = new Guid("7f8250de-1646-4a70-b675-fc13d7bfa94d"),
                            CreatedAt = new DateTime(2025, 9, 27, 8, 1, 5, 812, DateTimeKind.Utc).AddTicks(2171),
                            CreatorId = new Guid("7f8250de-1646-4a70-b675-fc13d7bfa94d"),
                            Description = "Task board columns",
                            Priority = "LOW",
                            Status = 0,
                            Title = "Frontend dashboard",
                            UpdatedAt = new DateTime(2025, 9, 27, 8, 1, 5, 812, DateTimeKind.Utc).AddTicks(2171)
                        },
                        new
                        {
                            Id = new Guid("4ccd9459-ffa9-48a8-be2c-fb01db8d47d5"),
                            AssigneeId = new Guid("7f8250de-1646-4a70-b675-fc13d7bfa94d"),
                            CreatedAt = new DateTime(2025, 9, 27, 8, 1, 5, 812, DateTimeKind.Utc).AddTicks(2174),
                            CreatorId = new Guid("8ab106de-325b-48d8-9fe5-08099049fe89"),
                            Description = "Update CI/CD pipeline",
                            Priority = "HIGH",
                            Status = 0,
                            Title = "Update CI/CD",
                            UpdatedAt = new DateTime(2025, 9, 27, 8, 1, 5, 812, DateTimeKind.Utc).AddTicks(2174)
                        },
                        new
                        {
                            Id = new Guid("a36d73ab-49b1-41f8-8cec-611f03957765"),
                            AssigneeId = new Guid("8ab106de-325b-48d8-9fe5-08099049fe89"),
                            CreatedAt = new DateTime(2025, 9, 27, 8, 1, 5, 812, DateTimeKind.Utc).AddTicks(2185),
                            CreatorId = new Guid("8ab106de-325b-48d8-9fe5-08099049fe89"),
                            Description = "Validate all user Data",
                            Priority = "MEDIUM",
                            Status = 1,
                            Title = "DB Validation",
                            UpdatedAt = new DateTime(2025, 9, 27, 8, 1, 5, 812, DateTimeKind.Utc).AddTicks(2185)
                        },
                        new
                        {
                            Id = new Guid("7f0978e8-c3bf-4865-9155-378e6513b2da"),
                            AssigneeId = new Guid("7f8250de-1646-4a70-b675-fc13d7bfa94d"),
                            CreatedAt = new DateTime(2025, 9, 27, 8, 1, 5, 812, DateTimeKind.Utc).AddTicks(2187),
                            CreatorId = new Guid("8ab106de-325b-48d8-9fe5-08099049fe89"),
                            Description = "JWT authentication validation",
                            Priority = "HIGH",
                            Status = 2,
                            Title = "Auth Validation",
                            UpdatedAt = new DateTime(2025, 9, 27, 8, 1, 5, 812, DateTimeKind.Utc).AddTicks(2188)
                        },
                        new
                        {
                            Id = new Guid("6112daa4-efb5-4a44-8e80-060404e85edc"),
                            AssigneeId = new Guid("7f8250de-1646-4a70-b675-fc13d7bfa94d"),
                            CreatedAt = new DateTime(2025, 9, 27, 8, 1, 5, 812, DateTimeKind.Utc).AddTicks(2190),
                            CreatorId = new Guid("7f8250de-1646-4a70-b675-fc13d7bfa94d"),
                            Description = "Task board columns",
                            Priority = "LOW",
                            Status = 0,
                            Title = "Task Board",
                            UpdatedAt = new DateTime(2025, 9, 27, 8, 1, 5, 812, DateTimeKind.Utc).AddTicks(2190)
                        });
                });

            modelBuilder.Entity("TaskManagement.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8ab106de-325b-48d8-9fe5-08099049fe89"),
                            CreatedAt = new DateTime(2025, 9, 27, 8, 1, 5, 468, DateTimeKind.Utc).AddTicks(484),
                            Email = "admin@example.com",
                            PasswordHash = "$2a$11$3B94RS298Kp/oez//VGz7.9aM1F75l2f8EdUiii.0DbXiJSCNpe8W",
                            Role = 1,
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("7f8250de-1646-4a70-b675-fc13d7bfa94d"),
                            CreatedAt = new DateTime(2025, 9, 27, 8, 1, 5, 647, DateTimeKind.Utc).AddTicks(9196),
                            Email = "user@example.com",
                            PasswordHash = "$2a$11$SVnSHDmSzZLXDiV0..YCDuzTkEd8Sd4LsCizF9uhDoQ7QSoMr1c0i",
                            Role = 0,
                            Username = "user"
                        });
                });

            modelBuilder.Entity("TaskManagement.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("TaskManagement.Domain.Entities.User", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeId");

                    b.HasOne("TaskManagement.Domain.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId");

                    b.Navigation("Assignee");

                    b.Navigation("Creator");
                });
#pragma warning restore 612, 618
        }
    }
}
